---
# Style configuration
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier
  - plugin:@typescript-eslint/recommended

plugins:
  - "@typescript-eslint/eslint-plugin"
  - import

rules:
  # Configure required extensions
  import/extensions:
    - warn
    - ts: never

  # Too pedantic / sometimes encourages Node anti-patterns
  import/prefer-default-export: off
  no-await-in-loop: off
  no-restricted-syntax: off
  class-methods-use-this: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  # Configure no-use-before-define
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
    - typedefs: false
      ignoreTypeReferences: true
      functions: false
      classes: false

# ESLint Project Settings
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    modules: true
